/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package baithuchanhso3;

import baithuchanhso3.model.repository.StudentRepository;
import baithuchanhso3.model.utils.DBUtils;
import baithuchanhso3.view.Menu2;

public class RunMenu2 {
    public static void main(String[] args) {
        DBUtils.instance.SetUsernamePassword("root", "ComTMM0112");
        StudentRepository studentRepository = new StudentRepository();
        Menu2 menu2 = new Menu2(studentRepository);
        menu2.setVisible(true);
    }
}
